/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaplayer2;

import estructuras.Lista;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alfonso
 */
public class Player extends javax.swing.JFrame {

  private Lista listaPlayer;
  private Thread t;

  /**
   * Creates new form Player
   */
  public Player() {
    initComponents();
    iniciar();
  }

  private void iniciar() {

    listaPlayer = new Lista();

  }

  
  public void metodoGit(){
    /*
    
    
      ñajdhñakjfghañf
    ga
    fg
    af
    g
    af
    g
    af
    gs
    gagfgñladfkgjñaldkfjgñaklf
    
    
    
    */
  }
  
  
  
  
  private void controlarTabla() throws Exception {

    DefaultTableModel dtm
            = new DefaultTableModel(new String[]{"Title"}, 0);

    int rows = listaPlayer.getTam();

    for (int i = 0; i < rows; i++) {

      Object[] row = new Object[1];

      row[0] = listaPlayer.getValor(i);

      dtm.addRow(row);

    }

    tablaPlayer.setModel(dtm);

  }

  private String agregarPista() {

    String mp3 = "";
    JFileChooser fileChooser = new JFileChooser();

    fileChooser.setCurrentDirectory(
            new File(
                    System.getProperty("user.home")
            )
    );

    fileChooser.setDialogTitle("Abrir MP3");

    fileChooser.setMultiSelectionEnabled(false);

    FileNameExtensionFilter filter
            = new FileNameExtensionFilter("Archivos MP3", "mp3");

    fileChooser.setFileFilter(filter);

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
      mp3 = fileChooser.getSelectedFile().getAbsolutePath();
    }

    return mp3;

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    tablaPlayer = new javax.swing.JTable();
    agregar = new javax.swing.JButton();
    reproducir = new javax.swing.JButton();
    cerrar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    tablaPlayer.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Title"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tablaPlayer);
    if (tablaPlayer.getColumnModel().getColumnCount() > 0) {
      tablaPlayer.getColumnModel().getColumn(0).setResizable(false);
    }

    agregar.setText("Agregar");
    agregar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        agregarActionPerformed(evt);
      }
    });

    reproducir.setText("Reproducir");
    reproducir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reproducirActionPerformed(evt);
      }
    });

    cerrar.setText("Cerrar");
    cerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cerrarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(reproducir, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
          .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(agregar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(reproducir)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cerrar))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed

    // Cerrar la aplicación
    System.exit(0);

  }//GEN-LAST:event_cerrarActionPerformed

  private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

    try {

      listaPlayer.agregarAlFinal(agregarPista());

      controlarTabla();
    
    
    } catch (Exception ex) {
      Logger.getLogger(Player.class.getName()).log(Level.SEVERE, null, ex);
    }

  }//GEN-LAST:event_agregarActionPerformed

  private void reproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproducirActionPerformed

    // Reproducir
    t = new MediaControl(listaPlayer);
    
    t.start();

  }//GEN-LAST:event_reproducirActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton agregar;
  private javax.swing.JButton cerrar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton reproducir;
  private javax.swing.JTable tablaPlayer;
  // End of variables declaration//GEN-END:variables
}
